# Generated by Django 3.0.8 on 2025-07-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "string",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("lon", models.FloatField(blank=True, default=None, null=True)),
                ("lat", models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="all_day",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
