COLORS = {
    "afpyro": {"bg": "#133F52", "fg": "#FFFFFF"},
    "agenda_du_libre_be": {"bg": "#3A87AD", "fg": "white"},
    "agile_belgium": {"bg": "#D2353A", "fg": "white"},
    "bescala": {"bg": "#FEE63C", "fg": "#000000"},
    "bhackspace": {"bg": "DarkGoldenRod", "fg": "white"},
    "bxlug": {"bg": "white", "fg": "#990000"},
    "constantvzw": {"bg": "#D2C7BA", "fg": "black"},
    "foam": {"bg": "#C9C4BF", "fg": "black"},
    "hsbxl": {"bg": "coral", "fg": "white"},
    "incubhacker": {"bg": "#296038", "fg": "#6FCE91"},
    "laravel_brussels": {"bg": "#FFFFFF", "fg": "#FB503B"},
    "neutrinet": {"bg": "DarkBlue", "fg": "white"},
    "okno": {"bg": "#FFFFFF", "fg": "#00AA00"},
    "opengarage": {"bg": "DarkOrchid", "fg": "white"},
    "ruby_burgers": {"bg": "white", "fg": "#6F371F"},
    "urlab": {"bg": "pink", "fg": "black"},
    "voidwarranties": {"bg": "#25272C", "fg": "#C58723"},
    "whitespace": {"bg": "white", "fg": "black"},
    "wolfplex": {"bg": "#666661", "fg": "black"},
    "opentechschool": {"bg": "#3987CB", "fg": "white"},
}
